### ISSUE TITLE
Seems to break when using the ember-concurrency new api

### ISSUE THREAD

**Issue by mayatron** [kategengler/ember-cli-code-coverage#361] opened 2022-09-02 05:01 UTC
When using `ember-concurrency@2.3.2` with the [new API recently introduced](https://github.com/machty/ember-concurrency/blob/master/CHANGELOG.md), using `ember-cli-code-coverage@2.0.0-beta.4` seems to transpile the code in a way that `ember-concurrency` doesn't like.

Setting up a new app with something basic like:

```js
import Route from '@ember/routing/route';
import { task } from 'ember-concurrency';

export default class Application extends Route {
  model() {
    return this.myCoolTask.perform();
  }

  myCoolTask = task(async () => {
    return 'foo';
  });
}
```

If I write a basic test for this, and run without code coverage, I get:

```js
ember test
Environment: test
cleaning up...
Built project successfully.
ok 1 Chrome 104.0 - [236 ms] - Acceptance | Foo: it renders the text "foo"
ok 2 Chrome 104.0 - [1 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly

1..2
# tests 2
# pass  2
# skip  0
# todo  0
# fail  0

# ok
```

But with code coverage:

```js
COVERAGE=true ember test
Environment: test
cleaning up...
Built project successfully.
not ok 1 Chrome 104.0 - [382 ms] - Acceptance | Foo: it renders the text "foo"
    ---
        actual: >
            null
        stack: >
            Error: Assertion Failed: It appears you're attempting to use the new task(async () => { ... }) syntax, but the async arrow task function you've provided is not being properly compiled by Babel.

            Possible causes / remedies:

            1. You must pass the async function expression directly to the task() function (it is not currently supported to pass in a variable containing the async arrow fn, or any other kind of indirection)
            2. If this code is in an addon, please ensure the addon specificies ember-concurrency "2.3.0" or higher in "dependencies" (not "devDependencies")
            3. Ensure that there is only one version of ember-concurrency v2.3.0+ being used in your project (including nested dependencies) and consider using npm/yarn/pnpm resolutions to enforce a single version is used
                at assert (http://localhost:7357/assets/test-support.js:283:15)
                at task (http://localhost:7357/assets/vendor.js:92614:94)
                at new Application (http://localhost:7357/assets/foo.js:1877:96)
                at Application.create (http://localhost:7357/assets/vendor.js:23979:20)
                at FactoryManager.create (http://localhost:7357/assets/vendor.js:958:25)
                at Proxy.create (http://localhost:7357/assets/vendor.js:736:18)
                at instantiateFactory (http://localhost:7357/assets/vendor.js:842:71)
                at lookup (http://localhost:7357/assets/vendor.js:766:12)
                at Container.lookup (http://localhost:7357/assets/vendor.js:633:14)
                at ApplicationInstance.lookup (http://localhost:7357/assets/vendor.js:22148:33)
        message: >
            Promise rejected during "it renders the text "foo"": Assertion Failed: It appears you're attempting to use the new task(async () => { ... }) syntax, but the async arrow task function you've provided is not being properly compiled by Babel.

            Possible causes / remedies:

            1. You must pass the async function expression directly to the task() function (it is not currently supported to pass in a variable containing the async arrow fn, or any other kind of indirection)
            2. If this code is in an addon, please ensure the addon specificies ember-concurrency "2.3.0" or higher in "dependencies" (not "devDependencies")
            3. Ensure that there is only one version of ember-concurrency v2.3.0+ being used in your project (including nested dependencies) and consider using npm/yarn/pnpm resolutions to enforce a single version is used
        negative: >
            false
        browser log: |
    ...
ok 2 Chrome 104.0 - [1 ms] - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly

1..2
# tests 2
# pass  1
# skip  0
# todo  0
# fail  1
Testem finished with non-zero exit code. Tests failed.
```

Am I missing something? Or is this an issue with the babel transpilation from this addon?

**Comment by esbanarango** [comment] 2022-09-02 13:20
Same issue here:

On the left is the transpiled code using `COVERAGE` flag.

![image](https://user-images.githubusercontent.com/1156865/188153416-c5ddbe6a-d243-4375-8f08-104295c1036b.png)

Is there maybe a way to configure the order instanbul adds the `cov_**` wrappers.

**Comment by olyckne** [comment] 2022-09-07 09:45
I made a reproduction repo with a new ember app with 1.0.3 (but the problem exists in 2.0 as well):
 https://github.com/olyckne/ember-concurrency-arrow-fn-code-coverage-issue

**Comment by oliverlj** [comment] 2023-01-11 11:08
Seems to be fixed with https://github.com/machty/ember-concurrency/issues/483 ?

**Comment by esbanarango** [comment] 2023-02-23 18:32
We can probably close this now. https://github.com/machty/ember-concurrency/issues/483 fixed this issue

**Comment by kategengler** [comment] 2023-02-23 18:46
Thanks!

**Closed by kategengler** 2023-02-23 18:46 UTC
