### ISSUE TITLE
Running Ember CLI Code Coverage in Docker container

### ISSUE THREAD

**Issue by jbelmont** [kategengler/ember-cli-code-coverage#134] opened 2017-08-14 16:55 UTC
Currently I have the following build information

package.json dependencies:
```json
"devDependencies": {
    "autoprefixer": "^6.7.4",
    "broccoli-asset-rev": "^2.4.5",
    "broccoli-funnel": "1.1.0",
    "broccoli-less-single": "^0.6.3",
    "broccoli-merge-trees": "~2.0.0",
    "d3": "^4.4.6",
    "ember-ajax": "^2.4.1",
    "ember-cli": "~2.12.0",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-code-coverage": "0.3.11",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-less": "^1.5.3",
    "ember-cli-moment-shim": "^3.3.1",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^1.0.0-beta.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-test-loader": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-concurrency": "^0.8.7",
    "ember-data": "^2.9.0",
    "ember-disable-prototype-extensions": "^1.1.0",
    "ember-exam": "^0.6.0",
    "ember-export-application-global": "^2.0.0",
    "ember-intl": "^2.21.1",
    "ember-load-initializers": "^1.0.0",
    "ember-moment": "7.3.0",
    "ember-pikaday": "^2.2.2",
    "ember-resolver": "^4.0.0",
    "ember-sinon": "0.x.x",
    "ember-tether": "^0.4.0",
    "ember-truth-helpers": "1.3.0",
    "ember-webrtc-devices": "^5.2.0",
    "ember-webrtc-troubleshoot": "^4.1.0",
    "istanbul": "^0.4.5",
    "loader.js": "^4.0.10",
    "pre-commit": "^1.2.2",
    "pre-push": "^0.1.1",
    "semistandard": "^10.0.0"
  },
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "bower": "^1.8.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-uuid": "1.0.0",
    "testem-time-reporter": "^1.2.12"
  }
```

I have ember-cli-code-coverage pinned to 0.3.11 because coverage won't build on 0.4.

I am running ember tests in  a Jenkins Build inside a docker container.

```dockerfile
FROM node:6.11-slim

LABEL maintainer "marcelbelmont@gmail.com"

# Set Environment variables
ENV appDir /app

# Expose port 9222
EXPOSE 9222

# Set the work directory
RUN mkdir -p ${appDir}
WORKDIR ${appDir}

## Install dependencies
RUN \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
    apt-get update && \
    apt-get install -y google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get install python && \
    apt-get update && \
    apt-get install -y yarn git

## Add package json to docker container
COPY . ${appDir}

## Copy npmrc
COPY .npmrc ${appDir}/.npmrc

## Copy package.json into the container
COPY package.json ${appDir}/package.json

## Copy bower.json into the container
COPY bower.json ${appDir}/bower.json

# Allow root
RUN echo '{ "allow_root": true }' > ${appDir}/.bowerrc

RUN npm install -g bower

RUN yarn install --pure-lockfile
RUN bower install

## Force node-sass because it complains about needing to have binding Ugh
RUN npm rebuild node-sass --force

CMD ["yarn", "run", "test-fast"]
```

I can successfully run ember tests in the docker container but I can't seem to get code coverage to run and I am seeing this error

```
Unable to cover: ember-webrtc-components/components/webrtc-conversation/component.js . Try setting useBabelInstrumenter to true.
 TypeError: The plugin {"_parallelBabel":{"requireFile":"/app/node_modules/ember-cli-htmlbars-inline-precompile/lib/require-from-worker","buildUsing":"build","params":{"templateCompilerPath":"/app/bower_components/ember/ember-template-compiler","parallelConfig":[]}}} didn't export a Plugin instance
    at PluginManager.validate (/app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/app/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/app/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/app/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Instrumenter.instrumentSync (/app/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:36:45)
    at CoverageInstrumenter.processString (/app/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:113:25)
    at CoverageInstrumenter.processFile (/app/node_modules/broccoli-filter/index.js:165:31)
    at asyncProcessFile (/app/node_modules/broccoli-filter/index.js:122:21)
    at tryCatch (/app/node_modules/rsvp/dist/rsvp.js:525:12)
```

**Comment by rwjblue** [comment] 2017-08-14 19:30
Closing this as a duplicate of #133 (we will track progress over there)...

**Closed by rwjblue** 2017-08-14 19:30 UTC

**Comment by jbelmont** [comment] 2017-08-14 19:32
@rwjblue Okay sounds good
