### ISSUE TITLE
Issue with ember-page-object 

### ISSUE THREAD

**Issue by mattmarcum** [kategengler/ember-cli-code-coverage#63] opened 2016-11-01 20:39 UTC
I'm getting a strange error that I can't debug when I turn code-coverage on.

```
not ok 439 PhantomJS 2.1 - Global error: error requiring file for coverage: acl/blueprints/page-object-component at http://localhost:4201/assets/acl/vendor.js, line 228
    ---
        Log: |
            { type: 'error',
              text: 'error requiring file for coverage: acl/blueprints/page-object-component at http://localhost:4201/assets/acl/vendor.js, line 228\n' }
    ...
```

Weird thing is that I'm not using `page-object-component` anywhere so I'm not sure why its getting tested or pulled in.  Also my project only has 438 tests so I'm guessing test 439 is one added by code-coverage?  I'm running ember-lts (2.8),  "ember-cli-code-coverage": "0.3.6",  "ember-cli-mocha": "^0.10.4", "ember-cli-page-object": "1.3.0", and also using the babel instrumentor.

Even weirder, when I load up tests in a browser I can actually see `acl/blueprints/page-object-component` in my devtools.

**Comment by mattmarcum** [comment] 2016-11-01 21:29
debugged this with @kategengler and traced it to some weirdness in ember-cli-page-object.  Its putting weird code in the app's name space.

**Comment by kategengler** [comment] 2016-11-01 22:08
That's part of it, but also the cause is the code added yesterday to require all files in the project (so that coverage % takes into account files that aren't tested at all). 

I think changing this throw to a warning would be a better middle ground: https://github.com/kategengler/ember-cli-code-coverage/blob/master/lib/templates/test-body-footer.html#L10

**Comment by kellyselden** [comment] 2016-11-01 22:13
I think I'm getting this issue with some unused mirage code as well FYI. The solution may be to remove the code, but I dunno.

**Comment by rwjblue** [comment] 2016-11-02 01:14
Ya, I think we should probably just not throw.  However, it almost certainly points out unused code (since if simply requiring throws it is very unlikely to be used).

**Comment by rwjblue** [comment] 2016-11-02 01:32
Should be fixed by https://github.com/kategengler/ember-cli-code-coverage/pull/64

**Closed** 2016-11-02 13:29 UTC
