### ISSUE TITLE
Coverage failing with version 0.3.6 and up

### ISSUE THREAD

**Issue by rox163** [kategengler/ember-cli-code-coverage#75] opened 2016-11-07 20:42 UTC
I seem to have an issue with v 0.3.6+ of ember-cli-code-coverage. 
Running `COVERAGE=true ember test` kept failing after the last test was run ie when coverage would normally start. Its not repo specific. Doesnt matter what the tests are, this error always shows up at the end
```
not ok 29 Chrome 54.0 - FrostNavigationService "after each" hook
    ---
        message: >
            Uncaught TypeError: Cannot convert undefined or null to object (http://localhost:7357/5392/tests/index.html?hidepassed:43)
        stack: >
            Error: Uncaught TypeError: Cannot convert undefined or null to object (index.html?hidepassed:43)
                at global.onerror (http://localhost:7357/assets/test-support.js:8732:10)
        Log: |

```
I have pin pointed this to version 0.3.6 of ember-cli-code-coverage. Up to 0.3.5 everything works great. If you pin to v 0.3.5, coverage is reported properly.  Could be related to this PR https://github.com/kategengler/ember-cli-code-coverage/pull/62/files
@rwjblue @rwwagner90

**Comment by rwjblue** [comment] 2016-11-07 20:50
Can you tell me if `Object.keys(require.entries)` causes the same error?

If it does, this is likely the same (or related to the same root cause) as https://github.com/kategengler/ember-cli-code-coverage/issues/66.

**Comment by rox163** [comment] 2016-11-07 21:04
@rwjblue Not sure. What would you like me to do to test that `Object.keys` line?

**Comment by rwjblue** [comment] 2016-11-07 21:21
Run `ember test --server`, after your tests run in your browser open the console, type `Object.keys(require.entries)`. Is there an error?

**Comment by rox163** [comment] 2016-11-08 15:08
@rwjblue Yes there is an error.
![screen shot 2016-11-08 at 10 07 12 am](https://cloud.githubusercontent.com/assets/313318/20104241/3babba8a-a59b-11e6-8afd-81e9afd54520.png)

**Comment by rox163** [comment] 2016-11-08 15:18
Any suggestions on how to debug/work around this? As far as I can tell there is no custom `require` in my project directly but not sure about the dependent addons. We dont use yadda as was mentioned as the culprit in the other issue. 
I can point you to a project that has this failure when the coverage version is set to 0.3.6 - https://github.com/ciena-frost/ember-frost-navigation/blob/master/package.json.

**Comment by rox163** [comment] 2016-11-11 18:16
Related to https://github.com/kategengler/ember-cli-code-coverage/issues/66 as in my case it seems to be a conflict with mocha's require.

**Comment by offirgolan** [comment] 2016-12-08 03:40
Bump. I've been running into the same issue:

```bash
not ok 219 Chrome 54.0 - Global error: Uncaught TypeError: Cannot convert undefined or null to object at http://localhost:7357/assets/vendor.js, line 73209
    ---
        Log: |
            { type: 'error',
              text: 'Uncaught TypeError: Cannot convert undefined or null to object at http://localhost:7357/assets/vendor.js, line 73209\n' }
    ...
not ok 220 Chrome 54.0 - JSHint | unit/mixins/table-header-test.js: global failure
    ---
        actual: >
            null
        stack: >
            http://localhost:7357/assets/vendor.js:73209
        message: >
            Uncaught TypeError: Cannot convert undefined or null to object
        Log: |
    ...

```

**Comment by rwwagner90** [comment] 2016-12-08 13:05
@offirgolan are you using something that redefines the global `require`?

**Comment by offirgolan** [comment] 2016-12-09 02:21
When running what @rwjblue suggested

> Run ember test --server, after your tests run in your browser open the console, type Object.keys(require.entries). Is there an error?

I get the same error. `require.entries` is undefined. I do not believe I have any package that would redefine the global require either...

**Comment by a15n** [comment] 2017-01-31 23:25
I have made a PR to unblock those who are facing this issue. It's a simple `require.entries || {}` fix.

This doesn't fix any underlying issues with conflicting versions of require but it unblocks those who have conflicting versions.

**Comment by job13er** [comment] 2017-04-25 20:10
In case anyone else is still having an issue with an overwritten `require` and would like help tracking it down: I added the following to my `tests/index.html`

```html
<script>
    console = console || {}; // just in case
    console.watch = function(oObj, sProp) {
       sPrivateProp = "$_"+sProp+"_$"; // to minimize the name clash risk
       oObj[sPrivateProp] = oObj[sProp];

       // overwrite with accessor
       Object.defineProperty(oObj, sProp, {
           get: function () {
               return oObj[sPrivateProp];
           },

           set: function (value) {
               //console.log("setting " + sProp + " to " + value);
               debugger; // sets breakpoint
               oObj[sPrivateProp] = value;
           }
       });
    }

    console.watch(window, 'require')
</script>
```
And then ran my tests in the browser (I used `ember s -e test` but you could use `ember test --server` as well). The second `debugger` that was hit was my culprit. 

Still tracking down exactly where the file `browserfied-highlight.js` comes from, but in our case, it looks like that's the one causing problems.

**Comment by job13er** [comment] 2017-04-25 21:34
I opened https://github.com/ef4/ember-code-snippet/issues/34 to bring it to the attention of the authors of `ember-code-snippet`. In the meantime, I think I'll use a fork of that project that doesn't use `broccoli-browserify`

**Comment by job13er** [comment] 2017-04-27 11:52
As mentioned above, this has to do with other addons (in our case `brocolli-browserify`) overwriting `window.require`. I don't think it's actually anything this project wants to do anything about.  @rox163 You can probably close this guy.

**Closed** 2017-04-27 14:16 UTC
